/*
******************************************************************************
File:     main.c
Info:     Generated by Atollic TrueSTUDIO(R) 9.3.0   2023-09-10

The MIT License (MIT)
Copyright (c) 2019 STMicroelectronics

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
SOFTWARE.

******************************************************************************
*/

/* Includes */
#include "stm32f4xx.h"
#include "stm32f4_discovery.h"
#include "FreeRTOS.h"
#include "task.h"


/* Private macro */
/* Private variables */
TaskHandle_t  p_my_task_handle_1_st = NULL;
TaskHandle_t  p_my_task_handle_2_st = NULL;



/* Private function prototypes */
void task_1_handle_fp(void *params_vp);
void task_2_handle_fp(void *params_vp);


/* Private functions */

/**
**===========================================================================
**
**  Abstract: main program
**
**===========================================================================
*/
int main(void)
{


  // INIT
  RCC_DeInit();						// System clock 16MHz olarak ayarlandi
  SystemCoreClockUpdate();			// System clock update edildi


  /* Initialize LEDs */
  STM_EVAL_LEDInit(LED3);
  STM_EVAL_LEDInit(LED4);
  STM_EVAL_LEDInit(LED5);
  STM_EVAL_LEDInit(LED6);

  /* Turn on LEDs */
  STM_EVAL_LEDOn(LED3);
  STM_EVAL_LEDOn(LED4);
  STM_EVAL_LEDOn(LED5);
  STM_EVAL_LEDOn(LED6);



  //FreeRTOS INIT

  xTaskCreate( task_1_handle_fp,                // Function Pointer
               "Task_1",                        // Task name
			   configMINIMAL_STACK_SIZE,        // Stack size
               NULL                    ,        // Function Parameter
               1                       ,		// PRIORTY
			   &p_my_task_handle_1_st   );      // Task object


  xTaskCreate( task_2_handle_fp,                // Function Pointer
               "Task_2",                        // Task name
			   configMINIMAL_STACK_SIZE,        // Stack size
               NULL                    ,        // Function Parameter
               1                       ,		// PRIORTY
			   &p_my_task_handle_2_st   );      // Task object





  vTaskStartScheduler();







  /* Infinite loop */
  while (1)
  {

  }
}



//!< CREATED TASK BEGIN   <<



void task_1_handle_fp(void *params_vp)
{
	int a = 0;

	while(1)
	{
		a++;


	}
}


void task_2_handle_fp(void *params_vp)
{
	int b = 0;


	while(1)
	{
		b++;

	}
}



//!< CREATED TASK END    >>







/*
 * Callback used by stm32f4_discovery_audio_codec.c.
 * Refer to stm32f4_discovery_audio_codec.h for more info.
 */
void EVAL_AUDIO_TransferComplete_CallBack(uint32_t pBuffer, uint32_t Size){
  /* TODO, implement your code here */
  return;
}

/*
 * Callback used by stm324xg_eval_audio_codec.c.
 * Refer to stm324xg_eval_audio_codec.h for more info.
 */
uint16_t EVAL_AUDIO_GetSampleCallBack(void){
  /* TODO, implement your code here */
  return -1;
}
